Luxury_services/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('homepage');
});

Route::get('/profile', 'ProfileController@show')->name('profile.show');
Route::get('/profile/destroy', 'ProfileController@destroy')->name('profile.delete');
Route::post('/profile', 'ProfileController@store')->name('profile.store');

Auth::routes();

Route::get('/', 'HomeController@index')->name('homepage');
Route::get('/joboffers', 'JobOfferController@index')->name('joboffer');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/about-us', 'HomeController@company')->name('company');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
Route::get('joboffer/details', 'JobOfferController@show')->name('details');
Route::get('/admin', 'AdminController@show')->name('admin');
Route::get('/jobapplication/{id}', 'JobApplicationController@store');
Route::get('/admin/joboffers', 'AdminController@indexJobOffers')->name('admin.indexJobOffers');
Route::get('/admin/joboffer/{id}', 'AdminController@showJobOffer')->name('admin.showJobOffer');
Route::delete('/admin/joboffer/{id}', 'AdminController@destroyJobOffer')->name('admin.destroyJobOffer');
Route::get('/admin/clients', 'AdminController@showClients')->name('admin.clients');
Route::delete('/admin/clients/{id}', 'AdminController@destroyClient')->name('admin.destroyClient');
//Route::get('/admin/jobapplications{id}', 'AdminController@showJobApplications')->name('admin.jobapplications');

Route::resource('client', 'ClientController');
Route::resource('joboffer', 'JobOfferController');

Luxury_services/resources/views/jobs/index.blade.php
@extends('layouts.layout')
    @section('content')
        <!-- Page Content-->
        <section id="job-offers" class="section-padding gray-bg">
            <div class="container">
                <div class="text-center mb-40">
                    <h2 class="section-title">We have the perfect job for you</h2>
                    <p class="section-sub">just like our candidates, we offer quality, serious & reliable job offers.</p>
                </div>
                <div class="portfolio-container">
                    <ul class="portfolio-filter brand-filter text-center">
                        <li class="active waves-effect waves-light" data-group="all">All</li>
                        <li class=" waves-effect waves-light" data-group="Commercial">Commercial</li>
                        <li class=" waves-effect waves-light" data-group="Retail Sales">Retail Sales</li>
                        <li class=" waves-effect waves-light" data-group="Creative">Creative</li>
                        <li class=" waves-effect waves-light" data-group="Technology">Technology</li>
                        <li class=" waves-effect waves-light" data-group="Marketing & PR">Marketing & PR</li>
                        <li class=" waves-effect waves-light" data-group="Fashion & Luxury">Fashion & Luxury</li>
                        <li class=" waves-effect waves-light" data-group="Management & HR">Management & HR</li>
                    </ul>
                    
                    @if(session('error'))
                        <div class="btn btn-block btn-failed mt-30 waves-effect waves-light disabled">{{ session('error') }}</div>
                    @elseif(session('confirmation'))
                        <div class="btn btn-block btn-success mt-30 waves-effect waves-light disabled">{{ session('confirmation') }}</div>
                    @endif

                    <div class="portfolio portfolio-with-title col-2 gutter mt-30">
                    @forelse($jobsList as $jobs)
                        <div class="portfolio-item" data-groups='["all", "{{ $jobs->job_category }}"]'>
                            <div class="portfolio-wrapper">
                                <div class="card job-card">
                                    <div class="card-content">
                                        <span class="title">
                                            <span class="card-title">{{ $jobs->job_title }}</span>
                                            <span class="ref grey-text">Ref. {{ $jobs->id }}</span>
                                        </span>
                                        <div class="metas mb-20">
                                            <div class="meta">
                                                <i class="material-icons">&#xE53E;</i>{{ $jobs->salary }} &euro;
                                            </div>
                                            <div class="meta">
                                                <i class="material-icons">&#xE916;</i>{{ $jobs->closing_at }}
                                            </div>
                                            <div class="meta">
                                                <i class="material-icons">&#xE55F;</i>{{ $jobs->location }}
                                            </div>
                                        </div>
                                        <p class="truncate-text">{{ $jobs->description }}</p>
                                    </div>
                                    <div class="card-action">
                                        <a class="btn btn-md primary border waves-effect waves-dark" href="{{ route('joboffer.show', ['id' => $jobs->id]) }}">Details</a>
                                        @if (($totalRounded) == 100) 
                                            <a class="btn btn-md primary waves-effect waves-light" href="{{ url("jobapplication/" . $jobs->id )}}">Apply</a>
                                        @else
                                            <a class="btn btn-md primary waves-effect waves-light" href="{{ route('profile.show') }}">Apply</a>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    @empty
                        <p>No job offers available</p>
                    @endforelse
                        <div class="no-item"></div>
                    </div>
                </div>
            </div>
        </section>

        <section class="cta-candidate bg-fixed bg-cover overlay dark-5 padding-top-70 padding-bottom-50">
            <div class="container">
                <div class="row">
                    <div class="valign-wrapper text-center">
                        <div class="hero-intro valign-cell">
                            <h2 class="tt-headline clip is-full-width no-margin">
                                <span>You are </span>
                                <span class="tt-words-wrapper">
                                    <b class="is-visible">Commercial</b>
                                    <b>Creative</b>
                                    <b>Marketing & PR</b>
                                    <b>Technology</b>
                                    <b>Fashion & luxury</b>
                                    <b>Retail sales</b>
                                </span>
                            </h2>
                            <h3 class="c-secondary mb-30 no-margin">Sign-up and apply for jobs now</h3>
                            <p class="white-text section-sub">Each one of your skills is seen as precious resource to us, each one of your personality traits are considered as an added on value. Joining us is allowing our recruitment expertise and personal guidance to bring the best out in you by choosing the most suited position.</p>

                            <a href="{{ route('register') }}" class="btn border secondary waves-effect waves-light mt-40">Join us</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
@endsection

Luxury_services/resources/views/jobs/show.blade.php
@extends('layouts.layout')

@section('content')
    <!-- Page Content-->
    <section class="single-project-section section-padding light-gray-bg">
        <div class="container">
            <div class="project-overview">
                <div class="row mb-80">
                    <div class="col-xs-12 col-md-8">
                        <p class="ref grey-text no-margin">Ref. {{ $jobOffer->id }}</p>
                        <h2>{{ $jobOffer->job_title }}</h2>
                        <p>{{ $jobOffer->description }}</p>
                    </div>

                    <div class="col-xs-12 col-md-4 quick-overview">
                        <ul class="portfolio-meta">
                            <li><span> Pulished at </span>{{ $jobOffer->created_at }}</li>
                            <li><span> Position </span>{{ $jobOffer->job_title }}</li>
                            <li><span> Contract Type </span>{{ $jobOffer->job_type }}</li>
                            <li><span> Salary </span>{{ $jobOffer->salary }} &euro;</li>
                            <li><span> Location </span>{{ $jobOffer->location }}</li>
                            <li><span> Closing date </span>{{ $jobOffer->closing_at }}</li>
                        </ul>
                        
                        @if(session('error'))
                            <div class="btn btn-block btn-failed mt-30 waves-effect waves-light disabled">{{ session('error') }}</div>
                        @elseif(session('confirmation'))
                            <div class="btn btn-block btn-success mt-30 waves-effect waves-light disabled">{{ session('confirmation') }}</div>
                        @endif
                        
                        @if (($totalRounded) == 100 && $jobOffer !== 0) 
                            <a class="btn btn-block gradient primary mt-30 waves-effect waves-light" href="{{ url("jobapplication/".$jobOffer->id )}}">Apply for this job</a>
                        @else
                            <a class="btn btn-block gradient primary mt-30 waves-effect waves-light" href="{{ route('profile.show') }}">Apply for this job</a>
                        @endif
                        
                    </div>
                </div>
            </div>

            <nav class="single-post-navigation no-margin" role="navigation">
                <div class="row">

                    <div class="col-xs-6 col-sm-6 col-md-4">
                        <div class="previous-post-link">
                            <a class="btn border primary waves-effect waves-dark" href="{{ URL::to( '/joboffer/' . $previous ) }}">
                                <i class="fa fa-long-arrow-left"></i>Previous
                            </a>
                        </div>
                    </div>
                    <div class="hidden-xs hidden-sm col-md-4"></div>


                    <div class="col-xs-6 col-sm-6 col-md-4">
                        <div class="next-post-link">
                            <a class="btn border primary waves-effect waves-dark" href="{{ URL::to( '/joboffer/' . $next ) }}">
                                Next <i class="fa fa-long-arrow-right"></i>
                            </a>
                        </div>
                    </div>

                </div>
            </nav>
        </div>
    </section>
@endsection